version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Porta para acessar os serviços
      - "4571:4571"  # Porta para o DynamoDB
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"